version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: credit-simulator:latest
    container_name: creditsimulator
    ports:
      - "8080:8080"
    restart: unless-stopped
    
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./scripts:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: run /scripts/script.js

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data: